name: biren_kocluk
description: A new Flutter project.
publish_to: 'none'

version: 1.1.2+5

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Localization
  easy_localization: ^3.0.1
  
  #State Management
  path_provider: ^2.0.11

  #Firebase 
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth:
  firebase_storage: ^11.0.10

  #Image
  image_picker: ^0.8.7+1

  #Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  font_awesome_flutter: ^10.3.0

  #Utilty
  kartal: ^2.8.0
  awesome_dialog: ^3.0.2
  table_calendar: ^3.0.9
  intl:
  date_field: ^3.0.5
  awesome_snackbar_content:  
  syncfusion_flutter_pdfviewer:
  file_picker:
  shared_preferences: ^2.2.0
  calendar_timeline: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.0
  build_runner: ^2.3.2
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  image: assets/icons/logo.png
  color: "#f9f9f9"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/jsons/
    - assets/images/
    - assets/jsons/lang/
    - assets/jsons/study/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600