name: biren_kocluk
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Localization
  easy_localization: ^3.0.1
  
  #State Management
  path_provider: ^2.0.11
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1

  #Firebase 
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth:
  firebase_storage: ^11.0.10

  #Image
  image_picker: ^0.8.7+1

  #Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  font_awesome_flutter: ^10.3.0

  #Utilty
  kartal: ^2.8.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/jsons/
    - assets/images/
    - assets/jsons/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700