name: biren_kocluk
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Localization
  easy_localization: ^3.0.1
  
  #State Management
  path_provider: ^2.0.11
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1

  #Firebase 
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth:
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.4.0

  #Service
  flutter_local_notifications: ^13.0.0
  http: ^0.13.5

  #Image
  image_picker: ^0.8.7+1

  #Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  font_awesome_flutter: ^10.3.0

  #Utilty
  kartal: ^2.8.0
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.0.2
  loading_animation_widget: ^1.2.0+4
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.0
  build_runner: ^2.3.2
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/jsons/
    - assets/images/
    - assets/jsons/lang/
    - assets/jsons/study/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700