// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH8qSUoLzPtnC1bsZkoW2KVXTpMfOoBZc',
    appId: '1:997162249545:web:2c6b039978bf987c357e98',
    messagingSenderId: '997162249545',
    projectId: 'biren-d1ded',
    authDomain: 'biren-d1ded.firebaseapp.com',
    storageBucket: 'biren-d1ded.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLREmNa7sFAhmUkKsoyJyOmiD8tdfCpzw',
    appId: '1:997162249545:android:26f5cf4038091284357e98',
    messagingSenderId: '997162249545',
    projectId: 'biren-d1ded',
    storageBucket: 'biren-d1ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDen1skEkTvRLx64RId0QUR3eZKc3BjuVw',
    appId: '1:997162249545:ios:23eef40aea018abb357e98',
    messagingSenderId: '997162249545',
    projectId: 'biren-d1ded',
    storageBucket: 'biren-d1ded.appspot.com',
    iosClientId: '997162249545-gic82ftf3gskgos3gc30sg3ik2s5f4d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.birenKocluk',
  );
}
